server:
  port: 8081
  
app:
  cache:
#    type: caffeine    type: ehcache  
    ehcache:      config: classpath:/ehcache.xml
  jpa:    hibernate:      ddl-auto: update
    show-sql: true  datasource:
    primary:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@172.16.59.51:1521:orcl
      username: NC1119
      password: NC1119
#      hikari:      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 2000
      max-lifetime: 18000000
      maximum-pool-size: 20
      minimum-idle: 3
    secondary:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: long1
      password: qiushen
#      hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 2000
      max-lifetime: 18000000
      maximum-pool-size: 20
      minimum-idle: 3
     